services:
  audio_processor:
    build: .
    image: llm_planner_image:latest
    container_name: audio_processor_container

    devices:
      - /dev/snd:/dev/snd

    network_mode: "host"
    ipc: host

    environment:
      - VOSK_MODEL=${VOSK_MODEL}
      - AUDIO_SAMPLERATE=${AUDIO_SAMPLERATE}
      - AUDIO_BLOCK_SIZE=${AUDIO_BLOCK_SIZE}

      - PULSE_SERVER=${PULSE_SERVER}
      - AUDIO_DEVICE=${AUDIO_DEVICE}
      # - XDG_RUNTIME_DIR=/tmp
      # - PULSE_COOKIE=/tmp/pulse-cookie-dir/cookie
    volumes:
      - /dev/shm:/dev/shm
      - ${HOST_VOSK_MODELS_PATH}:/workspace/models
      - ./src:/workspace/src

      # - ${HOST_PULSE_SOCKET_PATH:-/run/user/1000/pulse}:/tmp/pulse
      - /mnt/wslg/PulseServer:/mnt/wslg/PulseServer

      - ./asound.conf:/etc/asound.conf:ro
      # - ./pulse-client.conf:/etc/pulse/client.conf:ro
    group_add:
      - audio
    restart: unless-stopped
    command: bash -c "source /opt/ros/humble/setup.bash && source /workspace/install/setup.bash && ros2 run audio_processor audio_processor"

  decomposer:
    image: llm_planner_image:latest
    container_name: decomposer_container
    depends_on:
      - audio_processor
    
    network_mode: "host"
    ipc: host
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

    environment:
      - LLM_API_URL=${LLM_API_URL}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      - SYS_PROMPT_PATH=${SYS_PROMPT_PATH}
    volumes:
      - /dev/shm:/dev/shm
      - ./src:/workspace/src
      - ./schemas:/workspace/schemas
    command: bash -c "source /opt/ros/humble/setup.bash && source /workspace/install/setup.bash && ros2 run decomposer decomposer"
    restart: unless-stopped

    
  simulation:
    image: llm_planner_image:latest
    container_name: simulation_container
    depends_on:
      - audio_processor
    
    devices:
      - /dev/dxg:/dev/dxg

    network_mode: "host"
    ipc: host
    
    environment:
      - DISPLAY=${DISPLAY}
      - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

      - TARGET_VIDEO_FPS=${TARGET_VIDEO_FPS}
      - TARGET_VIDEO_WIDTH=${TARGET_VIDEO_WIDTH}
      - TARGET_VIDEO_HEIGHT=${TARGET_VIDEO_HEIGHT}
    
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/lib/wsl:/usr/lib/wsl
      - ./src:/workspace/src
    
    command: bash -c "source /opt/ros/humble/setup.bash && source /workspace/install/setup.bash && ros2 launch /workspace/src/ur10e_scene/launch/start_scene.launch.py && ros2 run rqt_image_view rqt_image_view"   
    # command: bash -c "source /opt/ros/humble/setup.bash && source /workspace/install/setup.bash"     

  sam3_preprocessor:
    image: llm_planner_image:latest
    container_name: sam3_preprocessor_container
    depends_on:
      - audio_processor
    
    network_mode: "host"
    ipc: host

    environment:
      - CAMERA_RAW_TOPIC=${CAMERA_RAW_TOPIC}
      - TARGET_VIDEO_FPS=${TARGET_VIDEO_FPS}
      - TARGET_VIDEO_WIDTH=${TARGET_VIDEO_WIDTH}
      - TARGET_VIDEO_HEIGHT=${TARGET_VIDEO_HEIGHT}

    volumes:
      - /dev/shm:/dev/shm
      - ./src:/workspace/src
    
    command: bash -c "source /opt/ros/humble/setup.bash && source /workspace/install/setup.bash && ros2 run sam3_preprocessor preprocessor"

  sam3_bridge:
    image: llm_planner_image:latest
    container_name: sam3_bridge_container
    depends_on:
      - audio_processor
    
    network_mode: "host"
    ipc: host

    environment:
      - SAM3_SERVER_URL=${SAM3_SERVER_URL}
    
    volumes:
      - /dev/shm:/dev/shm
      - ./src:/workspace/src

    command: bash -c "source /opt/ros/humble/setup.bash && source /workspace/install/setup.bash && ros2 run sam3_bridge bridge"